import { useState } from 'react';
import { toast } from 'sonner';
import { RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import BranchSelect from '@/components/inventory/BranchSelect';
import { useBranches } from '@/context/BranchContext';
import { formatDateTime, formatQty } from '@/lib/format';
import { ApiError } from '@/lib/apiClient';
import {
  useApproveRequisition,
  useAutoGenerateRequisitions,
  useRequisitions,
} from '../hooks/useRequisitions';
import { RequisitionStatusBadge } from '../components/StatusBadge';
import QueryState from '../components/QueryState';
import { RequisitionStatus } from '../../../../shared/inventoryTypes';

const STATUS_FILTERS: (RequisitionStatus | 'all')[] = [
  'all',
  'pending',
  'approved',
];

export default function RequisitionsPage() {
  const { selectedBranchId } = useBranches();
  const [status, setStatus] = useState<RequisitionStatus | 'all'>('all');

  const { data, isLoading, error } = useRequisitions({
    branchId: selectedBranchId ?? undefined,
    status: status === 'all' ? undefined : status,
  });
  const autoGenerate = useAutoGenerateRequisitions();
  const approve = useApproveRequisition();

  const handleCheckLevels = async () => {
    try {
      const res = await autoGenerate.mutateAsync(selectedBranchId ?? undefined);
      toast.success(
        res.requisitions.length > 0
          ? `${res.requisitions.length} requisition(s) generated or updated`
          : 'Nothing needs reordering right now',
      );
    } catch (err) {
      toast.error(
        err instanceof ApiError
          ? err.message
          : 'Could not check reorder levels.',
      );
    }
  };

  const handleApprove = async (id: string) => {
    try {
      await approve.mutateAsync(id);
      toast.success('Requisition approved');
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Could not approve.');
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold">Purchase requisitions</h1>
          <p className="text-sm text-muted-foreground">
            Auto-generated when an item hits its reorder point.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <BranchSelect />
          <Button onClick={handleCheckLevels} disabled={autoGenerate.isPending}>
            <RefreshCw className="mr-1 h-4 w-4" />
            {autoGenerate.isPending ? 'Checking…' : 'Check reorder levels'}
          </Button>
        </div>
      </div>

      <Select
        value={status}
        onValueChange={(v) => setStatus(v as RequisitionStatus | 'all')}
      >
        <SelectTrigger className="w-48">
          <SelectValue />
        </SelectTrigger>
        <SelectContent>
          {STATUS_FILTERS.map((s) => (
            <SelectItem key={s} value={s} className="capitalize">
              {s === 'all' ? 'All statuses' : s}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>

      <QueryState
        isLoading={isLoading}
        error={error}
        isEmpty={(data?.requisitions.length ?? 0) === 0}
        emptyMessage='Nothing here — try "Check reorder levels".'
      >
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Lines</TableHead>
              <TableHead>Source</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Created</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {data?.requisitions.map((r) => (
              <TableRow key={r.id}>
                <TableCell className="text-xs text-muted-foreground">
                  {r.lines
                    .map(
                      (l) =>
                        `${l.item?.name ?? l.itemId}: ${formatQty(l.quantity, l.item?.stockUnit ?? 'unit')}`,
                    )
                    .join(', ')}
                </TableCell>
                <TableCell>
                  <Badge variant={r.isAutoGenerated ? 'secondary' : 'outline'}>
                    {r.isAutoGenerated ? 'Auto' : 'Manual'}
                  </Badge>
                </TableCell>
                <TableCell>
                  <RequisitionStatusBadge status={r.status} />
                </TableCell>
                <TableCell>{formatDateTime(r.createdAt)}</TableCell>
                <TableCell className="text-right">
                  {r.status === 'pending' && (
                    <Button
                      size="sm"
                      onClick={() => handleApprove(r.id)}
                      disabled={approve.isPending}
                    >
                      Approve
                    </Button>
                  )}
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </QueryState>
    </div>
  );
}
