export type ItemCategory =
  | 'spirit'
  | 'beer'
  | 'wine'
  | 'mixer'
  | 'food'
  | 'glassware'
  | 'consumable'
  | 'other';

export type StockUnit = 'bottle' | 'can' | 'keg' | 'case' | 'unit';

export interface Branch {
  id: string;
  name: string;
  code: string;
  isActive: boolean;
}

export interface BranchStock {
  quantityOnHand: string;
  reorderPoint: string;
  minLevel: string;
  maxLevel: string | null;
}

export interface InventoryItem {
  id: string;
  sku: string;
  name: string;
  category: ItemCategory;
  stockUnit: StockUnit;
  unitVolumeMl: number | null;
  costPrice: number;
  isPourable: boolean;
  defaultPourMl: number | null;
  expiryTracked: boolean;
  isActive: boolean;
  branchStock?: BranchStock | null;
}

export interface ItemListResult {
  items: InventoryItem[];
  total: number;
  limit: number;
  offset: number;
}

export type RecipeIngredientUnit = 'ml' | 'unit';

export interface RecipeIngredient {
  itemId: string;
  quantityUnit: RecipeIngredientUnit;
  quantity: number;
  item?: InventoryItem;
}

export interface Recipe {
  id: string;
  name: string;
  description: string | null;
  isActive: boolean;
  ingredients: RecipeIngredient[];
}

export type LossType =
  | 'breakage'
  | 'spoilage'
  | 'flat_beer'
  | 'return_to_supplier'
  | 'waste'
  | 'other';

export interface LossRecord {
  id: string;
  itemId: string;
  branchId: string;
  lossType: LossType;
  quantity: string;
  reasonCode: string;
  supplierCreditNoteRef?: string | null;
  notes?: string | null;
  valueLost: string;
  createdAt: string;
}

export type TransferStatus =
  | 'requested'
  | 'approved'
  | 'completed'
  | 'cancelled';

export interface TransferLine {
  itemId: string;
  quantity: string;
  item?: InventoryItem;
}

export interface Transfer {
  id: string;
  fromBranchId: string;
  toBranchId: string;
  status: TransferStatus;
  notes: string | null;
  lines: TransferLine[];
  createdAt: string;
}

export type RequisitionStatus = 'pending' | 'approved';

export interface RequisitionLine {
  itemId: string;
  quantity: string;
  item?: InventoryItem;
}

export interface Requisition {
  id: string;
  branchId: string;
  status: RequisitionStatus;
  isAutoGenerated: boolean;
  lines: RequisitionLine[];
  createdAt: string;
}

export type StockCountStatus = 'open' | 'submitted';

export interface StockCountLine {
  itemId: string;
  systemQuantity: string;
  countedQuantity: string | null;
  varianceValue?: string | null;
  item?: InventoryItem;
}

export interface StockCount {
  id: string;
  branchId: string;
  status: StockCountStatus;
  notes: string | null;
  lines: StockCountLine[];
  createdAt: string;
  submittedAt: string | null;
}

export interface ConsolidatedStockBranch {
  branchId: string;
  branchName: string;
  quantityOnHand: string;
  reorderPoint: string;
  minLevel: string;
  maxLevel: string | null;
}

export interface ConsolidatedStockItem {
  itemId: string;
  sku: string;
  name: string;
  category: ItemCategory;
  stockUnit: StockUnit;
  totalOnHand: number;
  branches: ConsolidatedStockBranch[];
}

export interface ExpiryWarning {
  itemId: string;
  itemName: string;
  branchId: string;
  branchName: string;
  batchCode: string | null;
  expiryDate: string;
  quantity: string;
}

export interface DeadStockItem {
  itemId: string;
  name: string;
  sku: string;
  quantityOnHand: string;
  sinceDays: number;
}

export interface ForecastResult {
  itemId: string;
  branchId: string;
  lookbackDays: number;
  avgDailyUsage: number;
  onHand: number;
  daysOfCover: number | null;
  suggestedOrderQuantity: number;
}

export interface PourVariance {
  id: string;
  itemId: string;
  branchId: string;
  defaultPourMl: number;
  actualPourMl: number;
  createdAt: string;
  flagReason: string | null;
}
